version: '3'

services:

  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
      app_net:
        ipv4_address: 172.16.238.2

  back:
    build: ./testapp
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.16.238.3
    
  front:
    build: ./testContainerAngular
    restart: always
    depends_on:
      - back
    networks:
      app_net:
        ipv4_address: 172.16.238.4

  web:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    restart: always
    depends_on:
      - front
    networks:
      app_net:
        ipv4_address: 172.16.238.5

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

