version: '3'

services:

  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  back:
    build: ./testapp
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    
  front:
    build: ./testContainerAngular
    restart: always
    depends_on:
      - back

  web:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    restart: always
    depends_on:
      - front
